#!/usr/bin/env python3
"""Emit playground/examples.js from examples/*.ting.

Usage: python3 tools/playground_examples.py
Commit the result; tests/docs.rs checks it is in sync. Examples that
read stdin or arguments are skipped (the browser has neither), and
imports of "../lib/..." become "lib/..." so the embedded stdlib
resolves them in the wasm build.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
OUT = ROOT / "playground" / "examples.js"


def included(src: str) -> bool:
    return 'read_file("-")' not in src and "args()" not in src


def main() -> None:
    entries = {}
    for path in sorted(EXAMPLES.glob("*.ting")):
        src = path.read_text()
        if not included(src):
            continue
        entries[path.stem] = src.replace('"../lib/', '"lib/')
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    OUT.write_text(
        "// Generated by tools/playground_examples.py from examples/*.ting.\n"
        "// Do not edit; regenerate.\n"
        f"const TING_EXAMPLES = {body};\n"
    )


if __name__ == "__main__":
    main()
